# Generated by Django 5.0.3 on 2024-03-09 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleSNS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sampleSNS.post'),
        ),
    ]
